### ISSUE TITLE
저희 사이트는 여전히 이모티콘 사용시 내용이 사라지네요.

### ISSUE THREAD

**Issue by wookho** [kijin/xe-fix-mysql-utf8#1]
애드온 설치 후 변화가 없는 듯 합니다.

**Comment by kijin** [comment]
혹시 XE의 기본 필터링 기능 외에 글이나 댓글 내용을 추가로 가공하는 뭔가가 있나요?

일단 애드온이 정상적으로 호출되고 있는지 확인하기 위해 36번째 줄을 아래와 같이 고친 후

```
Context::set('title', 'TEST'.utf8mb4_encode_main($title), true);
```

제목에 "TEST"가 붙어서 나오는지 확인해 주세요.

**Comment by wookho** [comment]
글 말고 댓글로 테스트는 안될까요? 저희는 글 작성시 푸시가 나가서여

**Comment by kijin** [comment]
댓글로 테스트하셔도 돼요. 댓글은 제목이 없으므로 그 밑에 content 부분을 수정하시면 됩니다.

애드온은 일부 모듈에서만 작동하도록 설정할 수도 있으니 그걸 활용하시면 편합니다.

**Comment by wookho** [comment]
@kijin 고쳐서 테스트 했더니 댓글 상단에 TEST 라고 나옵니다.

**Comment by kijin** [comment]
그럼 일단 댓글 내용을 변경하는 코드는 제대로 작동하고 있다는 뜻인데요...

31줄의 `'&#x'`를 `'x'`로 바꾸고 이모티콘을 입력하면 어떻게 나오나요? (`x12345`처럼 나와야 합니다.)

**Comment by wookho** [comment]
네. 잘리지 않고 x1f60a 가 출력되고 이후 글자도 잘리지 않았습니다.

**Comment by kijin** [comment]
번거로우시더라도 한 가지만 더 테스트해 주세요. 관리자 계정으로 이모티콘을 입력하면 정상인가요?

**Comment by wookho** [comment]
네. 게시판관리 권한인 관리그룹의 계정으로는 일반회원과 동일하구요.
최고관리권한 계정으로 이모티콘 사용시 정상적으로 입력 됩니다.

**Comment by kijin** [comment]
최고관리자일 때만 정상이라면 `removeHackTag()` 함수에서 이모티콘을 말아먹고 있다는 뜻이로군요.

원인을 파악했으니 저도 좀더 확인해 보도록 하겠습니다.

**Comment by kijin** [comment]
일반 회원이나 비회원이 글을 쓸 때도 정상 작동하도록 고쳤습니다. 확인 부탁드립니다.

이런 식으로 XE를 뜯어고치려면 몽키패치밖에 답이 없는 듯 ㅋㅋㅋ

**Comment by wookho** [comment]
감사합니다. 아주 잘되네요. 
그럼 글쓰기나 댓글 쓰기시 속도면에서 거의 변화가 없는 것은 동일한가요?
아니면 PC에서는 불필요하니 애드온을 사용하지 않는 것이 유리한가요? 요 부분이 다시 궁금해지네요 ㅋ

**Comment by kijin** [comment]
코드의 분량이 조금 늘어나긴 했지만 여전히 모두 조건문 안에 들어 있어서, 글쓰기와 댓글쓰기 등 반드시 필요한 액션이 아니면 아무 것도 실행되지 않습니다. 켜두셔도 페이지 로딩속도에 미치는 영향은 극히 적을 것으로 생각됩니다. (게다가 앞으로는 PC에서도 이모티콘이나 이상한 특수문자를 사용하는 일이 점점 늘어나지 않을까요?)

**Comment by wookho** [comment]
네. 로딩속도보다 글쓰기와 댓글쓰기시 여러 요청이 동시에 몰려 혼잡해질까 하는 생각이 들어서요.

**Comment by kijin** [comment]
글쓰기 속도에 미치는 영향도 거의 없을 거예요. 아주 간단한 문자 치환과 비트 연산뿐이기 때문에 코어에서 기본으로 호출하는 `removeHackTag()` 함수 실행 시간의 1/1000도 안 될 겁니다.

**Comment by wookho** [comment]
네. 좋은자료 감사합니다.
