### ISSUE TITLE
1.8.18 과 관련있는지 검토 부탁드립니다.

### ISSUE THREAD

**Issue by wookho** [kijin/xe-fix-mysql-utf8#2]
금일 한 회원이 이미티콘을 사용한 것으로 추정이 되는데요. 네모박스안에 X표시가 들어간 것으로 표시가됩니다.

페이지 소스보기해서 보니...

`겠다고&#x1f644;ㅎㅎㅎ`

이렇게 나오는데요.. 제가 테스트했을때는 이미티콘이 보이더라구요.

**Comment by kijin** [comment]
일단 저장은 제대로 되었고, [1F644](http://www.fileformat.info/info/unicode/char/1F644/browsertest.htm) 문자는 대부분의 PC 브라우저에서 엑박으로 보이는 것이 정상입니다.

**Comment by wookho** [comment]
@kijin 아.. 그런구군요. 다행입니다. 제 모바일에서도 그렇게 보여서 혹시나 했는데 이상이 없으니 다행입니다.
